export { default as Error } from './error/error'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Spinner } from './spinner/spinner'
export { default as Loading } from './loading/loading'
export * from './atoms/atoms'
